;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        c-indent-line-or-region
        ))

(setq mc/cmds-to-run-once
      '(
        beginning-of-buffer
        c-electric-lt-gt
        next-buffer
        ))
